### ISSUE TITLE
Fail golang test

### ISSUE THREAD

**Issue by v-grabko1999** [dannyvankooten/extemplate#5]
go version go1.14.6 windows/amd64
$ go test
--- FAIL: TestLookup (0.00s)
    template_test.go:32: Lookup: expected template, got nil
--- FAIL: TestExecuteTemplate (0.00s)
    template_test.go:41: ExecuteTemplate: extemplate: no template "child.tmpl"
--- FAIL: TestTemplates (0.00s)
    template_test.go:61: template not found in set: grand-child.tmpl
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x58fe92]

goroutine 12 [running]:
testing.tRunner.func1.1(0x5c95c0, 0x786810)
        C:/programing/sdk/go/src/testing/testing.go:988 +0x314
testing.tRunner.func1(0xc00010ea20)
        C:/programing/sdk/go/src/testing/testing.go:991 +0x400
panic(0x5c95c0, 0x786810)
        C:/programing/sdk/go/src/runtime/panic.go:969 +0x174
html/template.(*Template).escape(0x0, 0x0, 0x0)
        C:/programing/sdk/go/src/html/template/template.go:95 +0x42
html/template.(*Template).Execute(0x0, 0x643720, 0xc00005f9e0, 0x0, 0x0, 0x1, 0x502466)
        C:/programing/sdk/go/src/html/template/template.go:119 +0x36
github.com/dannyvankooten/extemplate.TestTemplates(0xc00010ea20)
        C:/Users/kolo/go/src/github.com/dannyvankooten/extemplate/template_test.go:65 +0x2d1
testing.tRunner(0xc00010ea20, 0x60f9f0)
        C:/programing/sdk/go/src/testing/testing.go:1039 +0xe3
created by testing.(*T).Run
        C:/programing/sdk/go/src/testing/testing.go:1090 +0x379
exit status 2
FAIL    github.com/dannyvankooten/extemplate    0.164s

**Comment by arisudesu** [comment]
Late answer, but neverless. The package is platform-dependent and it doesn't work properly on Windows. It assumes path separators as forward slashes, though templates scan returns back slashes on Windows. It ends up with invalid template paths.

**Comment by arisudesu** [comment]
Maybe it will be good to also have option to normalize all path separators to forward slashes (unix) - you know, it's easier to flip a single switch in code when coding for both Windows and unix, rather than replacing slashes in every template :)

**Comment by dannyvankooten** [comment]
@arisudesu I realised that a bit later as I was having trouble getting the tests to pass, so did just that in 388ab0c9ef170eb950c397dc7a659a36999bd368 .

Now the only thing remaining is the [example output test](e503fa84287fb51c18b3b7863891cbf5f7cfa318) which fails due to the multi-line characters on Windows, but I have no good answer for it as of now... Any ideas?

**Comment by arisudesu** [comment]
Seems to me this is behavior of git option `core.autocrlf`- on windows template files are checked out with CRLF, LF on unix. Try adding examples/.gitattributes file which contains `*.tmpl text eol=lf` to instruct git to always check out these files with LF endings.

**Comment by dannyvankooten** [comment]
Awesome, that worked flawlessly. Nice trick. Thank you @arisudesu!
